components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    TextCompletionUsecasesFormBase:
      properties:
        execution_type:
          $ref: '#/components/schemas/UsecasesExecutionType'
        prompt_params_list:
          items:
            type: object
          title: Prompt Params List
          type: array
        usecase_forms:
          items: {}
          title: Usecase Forms
          type: array
      required:
      - prompt_params_list
      - usecase_forms
      - execution_type
      title: TextCompletionUsecasesFormBase
      type: object
    TextCompletionUsecasesItem:
      properties:
        output_params_list:
          items:
            type: object
          title: Output Params List
          type: array
      required:
      - output_params_list
      title: TextCompletionUsecasesItem
      type: object
    UsecasesExecutionType:
      description: An enumeration.
      enum:
      - chain
      - parallel
      title: UsecasesExecutionType
    ValidationError:
      properties:
        loc:
          items:
            type: string
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.0.2
paths:
  /v1/text_completion:
    post:
      operationId: pass_through_usecase
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextCompletionUsecasesFormBase'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextCompletionUsecasesItem'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Pass Through Usecase
      tags:
      - text_completion
